ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

INSTALLDIR=usr/bin
USEFILE=$(PROJECT_ROOT)/usemsg

LIBS+=gf img socket FF-T2K m

define PINFO
PINFO DESCRIPTION=Graphics Framework splash screen app
endef

ifeq ($(OS), win32)
LIBS += ws2_32 gfpr gdi32
EXTRA_LIBVPATH+=$(PROJECT_ROOT)/../../../services/phfont/lib/FontFusion5.0a/win32/x86/a
else
EXTRA_LIBVPATH+=$(addsuffix $(filter .v7, $(suffix $(VARIANT1))), $(addsuffix /$(OS)/$(subst $(CPU)/a. ,$(CPU)/a,$(CPU)/a.$(filter le be,$(subst ., ,$(VARIANTS))) ),$(PROJECT_ROOT)/../../../services/phfont/lib/FontFusion5.0a)) \
$(addsuffix $(filter .v7, $(suffix $(VARIANT1))), $(addsuffix /$(OS)/$(subst $(CPU)/so. ,$(CPU)/so,$(CPU)/so.$(filter le be,$(subst ., ,$(VARIANTS))) ),$(PROJECT_ROOT)/../../../services/phfont/lib/FontFusion5.0a))
endif
WIN32_ENVIRON=mingw

include $(MKFILES_ROOT)/qmacros.mk
include $(MKFILES_ROOT)/qtargets.mk
#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################
