#
# There are copies of this Makefile in:
# 	hardware/devnp/Makefile, lib/io-pkt/Makefile, lib/io-pkt/sys/dev_qnx/Makefile, lib/io-pkt/sys/dev_nda/Makefile
# but the hardware/devnp version is the master and should be first in a BSP srclist file.
#
# Note: EARLY_DIRS needs to include early dirs required for both dev_qnx and dev_nda
#
LIST=DEVNP
EARLY_DIRS=ath_hal lib
include recurse.mk
