ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

INSTALLDIR=lib

define PINFO
PINFO DESCRIPTION=Keyboard mapping common library
endef

NAME=keymap

EXTRA_SILENT_VARIANTS+=sengine

include $(MKFILES_ROOT)/qmacros.mk
include $(MKFILES_ROOT)/qtargets.mk

-include $(PROJECT_ROOT)/roots.mk
#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################
ifndef DEVI_ROOT
DEVI_ROOT=$(PROJECT_ROOT)/..
endif

EXTRA_INCVPATH = $(DEVI_ROOT)/include $(DEVI_ROOT)/public $(DEVI_ROOT)/private


